/**
 * PDF Generator Constants
 *
 * Japanese business constants for PDF generation.
 */

export const JAPANESE_CONSTANTS = {
  /** 消費税率 / Consumption tax rate */
  CONSUMPTION_TAX_RATE: 0.1,
  /** デフォルト用紙サイズ / Default paper format */
  DEFAULT_FORMAT: 'A4' as const,
  /** デフォルト向き / Default orientation */
  DEFAULT_ORIENTATION: 'portrait' as const,

  /** デフォルトの供应商情報 / Default supplier information */
  DEFAULT_SUPPLIER: {
    name: 'EPACKAGE Lab',
    subBrand: 'by kanei-trade',
    companyName: '金井貿易株式会社',
    postalCode: '〒675-1112',
    address: '兵庫県加古郡稲美町六分一486',
    phone: 'TEL：050-1793-6500',
    email: 'info@package-lab.com',
    description: 'オーダーメイドバッグ印刷専門',
    registrationNumber: '',
  },

  /** 見積テンプレートテキスト / Quote template text */
  QUOTE_TEMPLATES: {
    ja: {
      title: '御　見　積　書',
      quoteNumber: '見積番号',
      issueDate: '発行日',
      expiryDate: '有効期限',
      customer: 'お客様',
      companyName: '会社名',
      address: '住所',
      contactPerson: '担当者',
      phone: '電話番号',
      email: 'メールアドレス',
      items: '明細',
      no: 'No.',
      itemName: '品名',
      description: ' description',
      quantity: '数量',
      unit: '単位',
      unitPrice: '単価',
      amount: '金額',
      subtotal: '小計',
      tax: '消費税(10%)',
      total: '合計',
      paymentTerms: 'お支払条件',
      deliveryDate: '納期',
      deliveryLocation: '納入場所',
      validityPeriod: '有効期間',
      remarks: '備考',
      supplier: '発行者',
    },
    en: {
      title: 'QUOTATION',
      quoteNumber: 'Quote Number',
      issueDate: 'Issue Date',
      expiryDate: 'Expiry Date',
      customer: 'Customer',
      companyName: 'Company Name',
      address: 'Address',
      contactPerson: 'Contact Person',
      phone: 'Phone',
      email: 'Email',
      items: 'Line Items',
      no: 'No.',
      itemName: 'Item Name',
      description: 'Description',
      quantity: 'Quantity',
      unit: 'Unit',
      unitPrice: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      tax: 'Consumption Tax (10%)',
      total: 'Total',
      paymentTerms: 'Payment Terms',
      deliveryDate: 'Delivery Date',
      deliveryLocation: 'Delivery Location',
      validityPeriod: 'Validity Period',
      remarks: 'Remarks',
      supplier: 'Issuer',
    },
  },

  /** 請求テンプレートテキスト / Invoice template text */
  INVOICE_TEMPLATES: {
    ja: {
      title: '請　求　書',
      invoiceNumber: '請求書番号',
      issueDate: '発行日',
      dueDate: '支払期限',
      billingTo: '請求先',
      shippingTo: '納品先',
      items: '明細',
      no: 'No.',
      itemName: '品名',
      description: ' Description',
      quantity: '数量',
      unit: '単位',
      unitPrice: '単価',
      amount: '金額',
      subtotal: '小計',
      tax: '消費税(10%)',
      total: '合計',
      paymentMethod: 'お支払方法',
      bankInfo: '振込口座',
      bankName: '銀行名',
      branchName: '支店名',
      accountType: '口座種類',
      accountNumber: '口座番号',
      accountHolder: '口座名義',
      remarks: '備考',
      supplier: '請求元',
      contactPerson: '担当者',
    },
    en: {
      title: 'INVOICE',
      invoiceNumber: 'Invoice Number',
      issueDate: 'Issue Date',
      dueDate: 'Payment Due Date',
      billingTo: 'Bill To',
      shippingTo: 'Ship To',
      items: 'Line Items',
      no: 'No.',
      itemName: 'Item Name',
      description: 'Description',
      quantity: 'Quantity',
      unit: 'Unit',
      unitPrice: 'Unit Price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      tax: 'Consumption Tax (10%)',
      total: 'Total',
      paymentMethod: 'Payment Method',
      bankInfo: 'Bank Information',
      bankName: 'Bank Name',
      branchName: 'Branch Name',
      accountType: 'Account Type',
      accountNumber: 'Account Number',
      accountHolder: 'Account Holder',
      remarks: 'Remarks',
      supplier: 'Invoice From',
      contactPerson: 'Contact Person',
    },
  },
};

