-- =====================================================
-- Error Logs Table Migration
-- =====================================================
-- クライアント側のエラーログを保存するテーブル
-- エラートラッキングとデバッグに使用
--
-- @version 1.0.0
-- @created 2026-01-11
-- =====================================================

-- Create error_logs table
CREATE TABLE IF NOT EXISTS public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Error Information
  error_name VARCHAR(255) NOT NULL,
  error_message TEXT NOT NULL,
  error_stack TEXT,
  error_code VARCHAR(100),
  error_digest VARCHAR(100),

  -- Component Stack (for React errors)
  component_stack TEXT,

  -- Request Context
  user_agent TEXT,
  url TEXT NOT NULL,

  -- Boundary Information
  boundary VARCHAR(100), -- 'root', 'member', 'admin', etc.
  is_global BOOLEAN DEFAULT FALSE,
  is_manual BOOLEAN DEFAULT FALSE,

  -- Additional Information
  additional_info TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Indexes for querying
  CONSTRAINT error_logs_created_at_check CHECK (created_at <= NOW())
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_error_logs_created_at ON public.error_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_error_logs_error_name ON public.error_logs(error_name);
CREATE INDEX IF NOT EXISTS idx_error_logs_url ON public.error_logs(url);
CREATE INDEX IF NOT EXISTS idx_error_logs_boundary ON public.error_logs(boundary);
CREATE INDEX IF NOT EXISTS idx_error_logs_is_global ON public.error_logs(is_global);
CREATE INDEX IF NOT EXISTS idx_error_logs_error_code ON public.error_logs(error_code);

-- Create index for recent errors (last 7 days)
CREATE INDEX IF NOT EXISTS idx_error_logs_recent
  ON public.error_logs(created_at DESC)
  WHERE created_at >= NOW() - INTERVAL '7 days';

-- Create index for critical errors
CREATE INDEX IF NOT EXISTS idx_error_logs_critical
  ON public.error_logs(created_at DESC)
  WHERE error_code IN ('AUTH_ERROR', 'DATABASE_ERROR', 'NETWORK_ERROR');

-- Add comments for documentation
COMMENT ON TABLE public.error_logs IS 'Client-side error logs for debugging and monitoring';

COMMENT ON COLUMN public.error_logs.id IS 'Unique identifier for the error log';
COMMENT ON COLUMN public.error_logs.error_name IS 'Name of the error (e.g., TypeError, ReferenceError)';
COMMENT ON COLUMN public.error_logs.error_message IS 'Error message';
COMMENT ON COLUMN public.error_logs.error_stack IS 'Stack trace of the error';
COMMENT ON COLUMN public.error_logs.error_code IS 'Custom error code (if applicable)';
COMMENT ON COLUMN public.error_logs.error_digest IS 'Error digest for Next.js errors';
COMMENT ON COLUMN public.error_logs.component_stack IS 'React component stack trace';
COMMENT ON COLUMN public.error_logs.user_agent IS 'User agent string from browser';
COMMENT ON COLUMN public.error_logs.url IS 'URL where the error occurred';
COMMENT ON COLUMN public.error_logs.boundary IS 'Error boundary that caught the error';
COMMENT ON COLUMN public.error_logs.is_global IS 'Whether this was a global error (Next.js error.tsx)';
COMMENT ON COLUMN public.error_logs.is_manual IS 'Whether this was manually logged';
COMMENT ON COLUMN public.error_logs.additional_info IS 'Additional context or information';
COMMENT ON COLUMN public.error_logs.created_at IS 'Timestamp when the error was logged';

-- Enable Row Level Security
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Create policy: Service role can insert error logs
CREATE POLICY "Service role can insert error logs"
  ON public.error_logs
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Create policy: Service role can view all error logs
CREATE POLICY "Service role can view all error logs"
  ON public.error_logs
  FOR SELECT
  TO service_role
  USING (true);

-- Create policy: Authenticated users can view their own error logs (optional)
CREATE POLICY "Users can view their own error logs"
  ON public.error_logs
  FOR SELECT
  TO authenticated
  USING (
    -- Users can only see errors from their own sessions
    -- This requires additional context like user_id, which can be added later
    false
  );

-- Create a function to clean up old error logs (optional)
CREATE OR REPLACE FUNCTION cleanup_old_error_logs()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Delete error logs older than 90 days
  DELETE FROM public.error_logs
  WHERE created_at < NOW() - INTERVAL '90 days';

  -- Log the cleanup
  RAISE NOTICE 'Old error logs cleaned up successfully';
END;
$$;

-- Add a comment for the cleanup function
COMMENT ON FUNCTION cleanup_old_error_logs() IS 'Cleanup function to remove error logs older than 90 days';

-- Grant execute permission on cleanup function to service role
GRANT EXECUTE ON FUNCTION cleanup_old_error_logs() TO service_role;

-- =====================================================
-- Usage Notes
-- =====================================================
--
-- To enable error logging, set the environment variable:
-- ENABLE_ERROR_LOGGING=true
--
-- To manually log an error:
-- POST /api/errors/log
-- {
--   "error": {
--     "name": "Error",
--     "message": "Something went wrong",
--     "stack": "...",
--     "code": "CUSTOM_ERROR"
--   },
--   "url": "https://example.com/page",
--   "userAgent": "Mozilla/5.0...",
--   "timestamp": "2026-01-11T00:00:00Z"
-- }
--
-- To clean up old error logs:
-- SELECT cleanup_old_error_logs();
--
-- To view recent errors:
-- SELECT * FROM public.error_logs
-- ORDER BY created_at DESC
-- LIMIT 100;
--
-- To view errors by type:
-- SELECT error_name, COUNT(*) as count
-- FROM public.error_logs
-- GROUP BY error_name
-- ORDER BY count DESC;
--
-- =====================================================
